name: Ejecutar cron cada 5 minutos

on:
  schedule:
    - cron: "*/5 * * * *"   # Cada 5 minutos
  workflow_dispatch:        # Permite ejecutarlo manualmente

jobs:
  ejecutar:
    runs-on: ubuntu-latest
    steps:
      - name: Llamar URL timerIEWC
        run: |
          curl -s https://iewccfdi.facturacionelectronelectronica.mx/timerIEWC.php
